#!/bin/bash
# TAGS =  Name, Project, Environment, Role, CostCentre
PROJECT=kplus
ENV=p
ROLE=web
CC=Nathan
INSTANCEID=$(curl -s 169.254.169.254/latest/meta-data/instance-id)
MY_IP=$(curl -s 169.254.169.254/latest/meta-data/local-ipv4)
DOMAINNAME=aws.kapintdc.com
	HOSTNAME=$PROJECT-10245-$ENV-$ROLE-$INSTANCEID
	hostname $HOSTNAME
	sed -i "s/HOSTNAME=.*/HOSTNAME=$HOSTNAME/" /etc/sysconfig/network
echo "$MY_IP $HOSTNAME.$DOMAINNAME $HOSTNAME" >> /etc/hosts
sed -i "s/search .*/search $DOMAINNAME/" /etc/resolv.conf

