#!/bin/bash
# TAGS =  Name, Project, Environment, Role, CostCentre
PROJECT=kplus
ENV=p
ROLE=web
CC=Nathan
INSTANCE_ID=$(curl -s 169.254.169.254/latest/meta-data/instance-id)
RESERVATION_ID=$(curl -s 169.254.169.254/latest/meta-data/reservation-id)
if [ ! -z $HOSTNAME ]; then
	# HOSTNAME=[PROJECT]-10245-[ENV]-[ROLE]-$INSTANCE_ID-$RESERVATION_ID
	hostname $HOSTNAME
	sed -i "s/HOSTNAME=.*/HOSTNAME=$HOSTNAME/" /etc/sysconfig/network
fi

