#!/bin/bash
INSTANCE_ID=$(curl -s 169.254.169.254/latest/meta-data/instance-id)
RESERVATION_ID=$(curl -s 169.254.169.254/latest/meta-data/reservation-id)
if [ ! -z $HOSTNAME ];
HOSTNAME=[PROJECT]10245[ENV][ROLE]$INSTANCE_ID-$RESERVATION_ID
hostname $HOSTNAME
sed -i "s/HOSTNAME=.*/HOSTNAME=$HOSTNAME/" /etc/sysconfig/network
fi
